PropensityReweighter:
    logging: True
    GBparams:
        n_estimators: 30
        learning_rate: 0.009
        max_depth: 20
        min_samples_leaf: 1
        n_folds: 3
             
ProScoreVectorizer:
    model: "google-bert/bert-base-uncased"
    tokenizer: "google-bert/bert-base-uncased"
    