experiment:
  seed: 1234
  n_setups: 10
  n_samples: 500
  reweighers:
#    - dummy
#    - importance
    - classifier
#    - kde
#    - density-ratio
    - calib-classifier
    - adversarial
    - folding-reweighter

  performance_models:
    - quadratic_nd
    - gaussian_nd
    - exp_decay_nd
    - sigmoid_nd

dataset:
  input_data_distribution: gaussian_nd
  mean_range: [-2, 2]
  cov_range: [0.1, 1]
  n_dim: 3
  model_performance: "" # to be filled recursively by the ones listed in experiment.performance_models
  max_setup_plots: 1
