experiment:
  seed: 1234
  n_setups: 10
  n_samples: 500
  reweighers:
#    - dummy
#    - importance
    - classifier
#    - kde
#    - density-ratio
    - calib-classifier
    - adversarial
    - folding-reweighter
    - modifiedhep-reweighter
  reweighers_configs:
    modifiedhep-reweighter:
      PropensityReweighter:
        logging: False
        GBparams:
          n_estimators: 30
          learning_rate: 0.009
          max_depth: 20
          min_samples_leaf: 1
          n_folds: 3
      ProScoreVectorizer:
        model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
        tokenizer: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

  performance_models:
    - quadratic_nd
    - gaussian_nd
    - exp_decay_nd
    - sigmoid_nd

dataset:
  input_data_distribution: gaussian_nd
  mean_range: [-2, 2]
  cov_range: [0.1, 1]
  n_dim: 3
  model_performance: "" # to be filled recursively by the ones listed in experiment.performance_models
  max_setup_plots: 1
